extern const GeoLayout koopa_cannon_geo[];
extern Lights1 koopa_cannon_sm64_material_001_lights;
extern u8 koopa_cannon_sex_texture_ci8[];
extern u8 koopa_cannon_sex_texture_ci8_pal_rgba16[];
extern Vtx koopa_cannon_000_displaylist_mesh_vtx_0[4];
extern Gfx koopa_cannon_000_displaylist_mesh_tri_0[];
extern Gfx mat_koopa_cannon_sm64_material_001[];
extern Gfx mat_revert_koopa_cannon_sm64_material_001[];
extern Gfx koopa_cannon_000_displaylist_mesh[];
extern Gfx koopa_cannon_material_revert_render_settings[];
