// 0x16000EA0
const GeoLayout key_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x9B, 100),
   GEO_OPEN_NODE(),
      GEO_SWITCH_CASE(32, geo_switch_anim_state),
      GEO_OPEN_NODE(),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin1_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin1_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin2_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin2_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin3_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin3_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin4_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin4_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin5_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin5_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin6_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin6_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin7_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin7_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin8_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin8_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin9_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin9_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin10_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin10_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin11_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin11_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin12_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin12_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin13_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin13_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin14_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin14_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin15_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin15_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin16_txt),
         GEO_DISPLAY_LIST(LAYER_ALPHA, key_coin16_txt),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
