#include "src/game/envfx_snow.h"

const GeoLayout totwc_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -36, 646, 190, totwc_dl_Circle_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 19, 811, 86, totwc_dl_Circle_002_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 19, 811, 86, totwc_dl_Circle_003_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -161, 532, 167, totwc_dl_Circle_004_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 39, 60, 1736, totwc_dl_Cube_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -628, 96, -33, totwc_dl_Cube_002_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, 306, 850, -86, totwc_dl_Plane_001_mesh),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_ALPHA, -397, 561, -137, totwc_dl_Plane_003_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout totwc_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_CLOSE, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, totwc_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, totwc_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, totwc_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, totwc_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
