#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"

#include "mist/geo.inc.c"
#include "explosion/geo.inc.c"
#include "butterfly/geo.inc.c"
#include "coin/geo.inc.c"
#include "warp_pipe/geo.inc.c"
#include "door/geo.inc.c"
#include "bowser_key/geo.inc.c"
#include "flame/geo.inc.c"
#include "blue_fish/geo.inc.c"
#include "leaves/geo.inc.c"
#include "mario_cap/geo.inc.c"
#include "number/geo.inc.c"
#include "mushroom_1up/geo.inc.c"
#include "star/geo.inc.c"
#include "key/geo.inc.c"
#include "dirt/geo.inc.c"
#include "transparent_star/geo.inc.c"
#include "white_particle/geo.inc.c"
#include "wooden_signpost/geo.inc.c"
#include "tree/geo.inc.c"

#include "spinning_cog/geo.inc.c"
#include "title/geo.inc.c"
#include "koopakid/geo.inc.c"
#include "prince_bobomb/geo.inc.c"
#include "tumbling_platform/geo.inc.c"
#include "goombablue/geo.inc.c"
#include "koopa_cannon/geo.inc.c"
#include "bookstack/geo.inc.c"
#include "crewmate/geo.inc.c"
#include "prince_bobomb2/geo.inc.c"
#include "evilheart/geo.inc.c"
#include "heart_clockhand/geo.inc.c"
#include "waterbed/geo.inc.c"
#include "weakscaffold/geo.inc.c"
#include "n64/geo.inc.c"